<?php

namespace ObsessionMainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AfficheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfficheRepository extends EntityRepository
{

    public function findLast10(){
        $affiches =$this->findBy(array(),array('id'=>'DESC'));
        $affichesFinale=array();
        $count=0;
        foreach ($affiches as $affiche){
            $count++;
            if($count>10)
                break;
            $affichesFinale[]=$affiche;
        }
        return $affichesFinale;
    }

}
