<?php

namespace ObsessionMainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRepository extends EntityRepository
{
    public function findAllOrder(){
        return $this->findBy(array(),array('ville'=>'ASC'));
    }
}
