<?php

namespace ObsessionMainBundle\Repository;

/**
 * MoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoisRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getFourMonths(){
        $mois=intval((new \DateTime())->format('m'));
        $lesMois=array();
        for($i=$mois;$i<($mois+4);$i++){
            if($i>12)
                $r=($i%12);
            else $r=$i;

            $lesMois[]=$this->findOneBy(array('id'=>$r));
        }
        return $lesMois;
    }
    
}
