<?php

namespace ObsessionMainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SoireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoireeRepository extends EntityRepository
{
    public function findFiveSoirees(){
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.date>=:date')
            ->setParameter('date',new \DateTime())
            ->orderBy('s.date')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }

    public function findByAnnee($annee){
        $date=new \DateTime($annee.'-01-01');
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.date>=:date')
            ->setParameter('date',$date)
            ->orderBy('s.date')
            ->getQuery()
            ->getResult();
    }

    public function findByAnneeMois($annee,$mois){
        $date=new \DateTime($annee.'-'.$mois.'-01');
        $moisTrente=array(2,4,6,9,11);
        if(in_array($mois,$moisTrente))
            $date2=new \DateTime($annee.'-'.$mois.'-30');
        else $date2=new \DateTime($annee.'-'.$mois.'-31');
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.date>=:date')
            ->setParameter('date',$date)
            ->andWhere('s.date<=:date2')
            ->setParameter('date2',$date2)
            ->orderBy('s.date')
            ->getQuery()
            ->getResult();
    }
    
    public function findByMois($mois){
        $moisActu=intval((new \DateTime())->format('m'));
        if($mois<=12 && $mois>=$moisActu){
            $annee=intval((new \DateTime())->format('Y'));
        }else{
            $annee=intval((new \DateTime())->format('Y'))+1;
        }
        return $this->findByAnneeMois($annee,$mois);
    }
    

}
