<?php

namespace ObsessionMainBundle\Repository;
use ObsessionMainBundle\Entity\Statistique;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findMois(){
        $mois=intval((new \DateTime())->format('m'));
        $annee=intval((new \DateTime())->format('Y'));
        $date=new \DateTime($annee.'-'.$mois.'-01');
        $moisTrente=array(2,4,6,9,11);
        if(in_array($mois,$moisTrente))
            $date2=new \DateTime($annee.'-'.$mois.'-30');
        else $date2=new \DateTime($annee.'-'.$mois.'-31');
        $res=$this->createQueryBuilder('s')
            ->select('s')
            ->where('s.date>=:date')
            ->setParameter('date',$date)
            ->andWhere('s.date<=:date2')
            ->setParameter('date2',$date2)
            ->orderBy('s.date')
            ->getQuery()
            ->getResult();
        $ret=new Statistique();
        $ret->setDate($date);
        $ret->setAccueil(0);
        $ret->setPresentation(0);
        $ret->setPhotos(0);
        $ret->setSoirees(0);
        $ret->setContacts(0);
        foreach ($res as $r){
            $ret->setAccueil($ret->getAccueil()+$r->getAccueil());
            $ret->setPresentation($ret->getPresentation()+$r->getPresentation());
            $ret->setPhotos($ret->getPhotos()+$r->getPhotos());
            $ret->setSoirees($ret->getSoirees()+$r->getSoirees());
            $ret->setContacts($ret->getContacts()+$r->getContacts());
        }
        return $ret;
    }
    
}
